# Generated by Django 5.0.6 on 2026-04-11 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_variants', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='catalogue.variant')),
            ],
            options={
                'ordering': ['variant__character__name', 'variant__unlock_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='ownedvariant',
            constraint=models.UniqueConstraint(fields=('user', 'variant'), name='unique_owned_variant_per_user'),
        ),
    ]
