# Generated by Django 5.0.6 on 2026-04-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_displayroom_shelfslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayroom',
            name='reaction_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
