# Generated by Django 5.0.6 on 2026-04-12 19:50

from django.db import migrations, models


ROOM_SLOT_LAYOUT = (
    {"slot_index": 7, "shelf_index": 1, "slot_code": "l2", "display_order": 1, "unlock_cost": 30, "default_unlocked": False},
    {"slot_index": 1, "shelf_index": 1, "slot_code": "l1", "display_order": 2, "unlock_cost": 15, "default_unlocked": False},
    {"slot_index": 2, "shelf_index": 1, "slot_code": "c", "display_order": 3, "unlock_cost": 0, "default_unlocked": True},
    {"slot_index": 3, "shelf_index": 1, "slot_code": "r1", "display_order": 4, "unlock_cost": 20, "default_unlocked": False},
    {"slot_index": 8, "shelf_index": 1, "slot_code": "r2", "display_order": 5, "unlock_cost": 40, "default_unlocked": False},
    {"slot_index": 9, "shelf_index": 2, "slot_code": "l2", "display_order": 1, "unlock_cost": 35, "default_unlocked": False},
    {"slot_index": 4, "shelf_index": 2, "slot_code": "l1", "display_order": 2, "unlock_cost": 20, "default_unlocked": False},
    {"slot_index": 5, "shelf_index": 2, "slot_code": "c", "display_order": 3, "unlock_cost": 50, "default_unlocked": False},
    {"slot_index": 6, "shelf_index": 2, "slot_code": "r1", "display_order": 4, "unlock_cost": 25, "default_unlocked": False},
    {"slot_index": 10, "shelf_index": 2, "slot_code": "r2", "display_order": 5, "unlock_cost": 45, "default_unlocked": False},
)


def backfill_room_slots(apps, schema_editor):
    DisplayRoom = apps.get_model("collection", "DisplayRoom")
    ShelfSlot = apps.get_model("collection", "ShelfSlot")

    for room in DisplayRoom.objects.all():
        existing_slots = {slot.slot_index: slot for slot in ShelfSlot.objects.filter(room=room)}

        for config in ROOM_SLOT_LAYOUT:
            slot = existing_slots.get(config["slot_index"])
            if slot is None:
                ShelfSlot.objects.create(
                    room=room,
                    slot_index=config["slot_index"],
                    shelf_index=config["shelf_index"],
                    slot_code=config["slot_code"],
                    display_order=config["display_order"],
                    unlock_cost=config["unlock_cost"],
                    is_unlocked=config["default_unlocked"],
                )
                continue

            slot.shelf_index = config["shelf_index"]
            slot.slot_code = config["slot_code"]
            slot.display_order = config["display_order"]
            slot.unlock_cost = config["unlock_cost"]
            if slot.slot_index <= 6:
                slot.is_unlocked = True
            else:
                slot.is_unlocked = config["default_unlocked"]
            slot.save(
                update_fields=[
                    "shelf_index",
                    "slot_code",
                    "display_order",
                    "unlock_cost",
                    "is_unlocked",
                ]
            )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('collection', '0003_displayroom_reaction_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelfslot',
            options={'ordering': ['room', 'shelf_index', 'display_order', 'slot_index']},
        ),
        migrations.AddField(
            model_name='shelfslot',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shelfslot',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shelfslot',
            name='shelf_index',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shelfslot',
            name='slot_code',
            field=models.CharField(default='c', max_length=12),
        ),
        migrations.AddField(
            model_name='shelfslot',
            name='unlock_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_room_slots, noop_reverse),
        migrations.AddConstraint(
            model_name='shelfslot',
            constraint=models.UniqueConstraint(fields=('room', 'shelf_index', 'slot_code'), name='unique_slot_code_per_shelf'),
        ),
    ]
