# Generated by Django 5.0.6 on 2026-04-13 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_shelfslot_options_shelfslot_display_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedVariantCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('render_mode', models.CharField(choices=[('normal', 'Normal'), ('unlit', 'Unlit'), ('wireframe', 'Wireframe')], default='normal', max_length=20)),
                ('hidden_parts', models.JSONField(blank=True, default=list)),
                ('morph_values', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owned_variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customization_state', to='collection.ownedvariant')),
            ],
            options={
                'ordering': ['owned_variant__variant__character__name', 'owned_variant__variant__unlock_order'],
            },
        ),
    ]
