# Generated by Django 5.0.6 on 2026-04-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='chapter_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quest',
            name='chapter_title',
            field=models.CharField(default='Chapter 1 - First Light', max_length=120),
        ),
    ]
