# Generated by Django 5.0.6 on 2026-04-11 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('archetype', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('lore_quote', models.CharField(max_length=255)),
                ('color_hex', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('scene_type', models.CharField(choices=[('base', 'Base'), ('school', 'School'), ('rainy_day', 'Rainy Day')], max_length=32)),
                ('unlock_order', models.PositiveSmallIntegerField()),
                ('rarity', models.CharField(choices=[('standard', 'Standard'), ('story', 'Story')], default='standard', max_length=32)),
                ('short_description', models.TextField()),
                ('model_file_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalogue.character')),
            ],
            options={
                'ordering': ['character__name', 'unlock_order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('character', 'slug'), name='unique_variant_slug_per_character'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('character', 'scene_type'), name='unique_variant_scene_per_character'),
        ),
    ]
