# Generated by Django 5.0.6 on 2026-04-17 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantAssetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_version', models.PositiveIntegerField(default=1)),
                ('parts_schema', models.JSONField(blank=True, default=list)),
                ('morph_schema', models.JSONField(blank=True, default=list)),
                ('animation_schema', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_profile', to='catalogue.variant')),
            ],
            options={
                'ordering': ['variant__character__name', 'variant__unlock_order', 'variant__name'],
            },
        ),
    ]
